//
//  UserListModels.swift
//  CoredataPOC
//
//  Created by Wipro on 12/12/19.
//  Copyright (c) 2019 wipro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UserList
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
        var orders: [CustomUser]

    }
    struct ViewModel
    {
        struct DisplayedOrder
        {
            var firstname: String
            var email: String
            var lastname: String
            
        }
        var displayedOrders: [DisplayedOrder]
    }
  }
}
