//
//  UserListPresenter.swift
//  CoredataPOC
//
//  Created by Wipro on 12/12/19.
//  Copyright (c) 2019 wipro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserListPresentationLogic
{
  func presentSomething(response: UserList.Something.Response)
}

class UserListPresenter: UserListPresentationLogic
{
  weak var viewController: UserListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: UserList.Something.Response)
  {
    var displayedOrders: [UserList.Something.ViewModel.DisplayedOrder] = []
    for order in response.orders {
        let viewModel = UserList.Something.ViewModel.DisplayedOrder(firstname: order.first_name, email: order.email, lastname: order.last_name)
        displayedOrders.append(viewModel)
    }
    let viewModel = UserList.Something.ViewModel(displayedOrders: displayedOrders)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
