//
//  CreateUserViewController.swift
//  CoredataPOC
//
//  Created by Wipro on 12/12/19.
//  Copyright (c) 2019 wipro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateUserDisplayLogic: class
{
  func displaySomething(viewModel: CreateUser.Something.ViewModel)
}

class CreateUserViewController: UIViewController, CreateUserDisplayLogic
{
  var interactor: CreateUserBusinessLogic?
  var router: (NSObjectProtocol & CreateUserRoutingLogic & CreateUserDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = CreateUserInteractor()
    let presenter = CreateUserPresenter()
    let router = CreateUserRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
    
    @IBOutlet var emailField: UITextField!
    @IBOutlet var firstNameField: UITextField!
    @IBOutlet var lastNameField: UITextField!

    // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    
    self.title = "Create User"
    
    doSomething()
  }
    
    @IBAction func createUserBtnAction(_ sender: UIButton) {
        let firstname = firstNameField.text!
        let lastname = lastNameField.text!

        let email = emailField.text!
        
        let request = CreateUser.Something.Request(createUserFields: CreateUser.CreateuserFields(firstname: firstname, lastname: lastname, email: email))
        interactor?.createOrder(request: request)
    }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
//    let request = CreateUser.Something.Request(createUserFields: <#CreateUser.CreateuserFields#>)
//    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: CreateUser.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
    router?.routeToSomewhere(segue: nil)
  }
}
