//
//  CreateUserInteractor.swift
//  CoredataPOC
//
//  Created by Wipro on 12/12/19.
//  Copyright (c) 2019 wipro. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateUserBusinessLogic
{
  func doSomething(request: CreateUser.Something.Request)
  func createOrder(request: CreateUser.Something.Request)

}

protocol CreateUserDataStore
{
  //var name: String { get set }
}

class CreateUserInteractor: CreateUserBusinessLogic, CreateUserDataStore
{
  var presenter: CreateUserPresentationLogic?
  var worker: CreateUserWorker?
  //var name: String = ""
  
  // MARK: Do something
    func createOrder(request: CreateUser.Something.Request) {
        worker = CreateUserWorker()
        worker?.doSomeWork()
        
        let userObj = CUsers()
        userObj.first_name = request.createUserFields.firstname
        userObj.last_name = request.createUserFields.lastname
        userObj.email = request.createUserFields.email

        CoreDataManager.sharedInstance.createUser(userData: userObj, compleationHandler: { (responce) -> Void in
            let response = CreateUser.Something.Response()
            self.presenter?.presentSomething(response: response)
        })

    }
  
  func doSomething(request: CreateUser.Something.Request)
  {
    worker = CreateUserWorker()
    worker?.doSomeWork()
    
    let response = CreateUser.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
